apiVersion: v1
kind: Service
metadata:
  name: devtinder-service
spec:
  selector:
    app: devtinder
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            # Kubernetes service port
      targetPort: 3000    # Container port (inside pod)
      nodePort: 30001